// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/funding.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Сообщение о ставке фандинга
type FundingRate struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Exchange       string                 `protobuf:"bytes,1,opt,name=exchange,proto3" json:"exchange,omitempty"`
	Symbol         string                 `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Rate           float64                `protobuf:"fixed64,3,opt,name=rate,proto3" json:"rate,omitempty"`
	Timestamp      int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Volume_24H     float64                `protobuf:"fixed64,5,opt,name=volume_24h,json=volume24h,proto3" json:"volume_24h,omitempty"`               // Объем за 24 часа в базовой валюте
	VolumeUsdt_24H float64                `protobuf:"fixed64,6,opt,name=volume_usdt_24h,json=volumeUsdt24h,proto3" json:"volume_usdt_24h,omitempty"` // Объем за 24 часа в USDT
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FundingRate) Reset() {
	*x = FundingRate{}
	mi := &file_proto_funding_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FundingRate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FundingRate) ProtoMessage() {}

func (x *FundingRate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_funding_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FundingRate.ProtoReflect.Descriptor instead.
func (*FundingRate) Descriptor() ([]byte, []int) {
	return file_proto_funding_proto_rawDescGZIP(), []int{0}
}

func (x *FundingRate) GetExchange() string {
	if x != nil {
		return x.Exchange
	}
	return ""
}

func (x *FundingRate) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *FundingRate) GetRate() float64 {
	if x != nil {
		return x.Rate
	}
	return 0
}

func (x *FundingRate) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *FundingRate) GetVolume_24H() float64 {
	if x != nil {
		return x.Volume_24H
	}
	return 0
}

func (x *FundingRate) GetVolumeUsdt_24H() float64 {
	if x != nil {
		return x.VolumeUsdt_24H
	}
	return 0
}

// Сообщение о настройках минимального фандинга
type MinFundingSettings struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	MinRate       float64                `protobuf:"fixed64,2,opt,name=min_rate,json=minRate,proto3" json:"min_rate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MinFundingSettings) Reset() {
	*x = MinFundingSettings{}
	mi := &file_proto_funding_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MinFundingSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MinFundingSettings) ProtoMessage() {}

func (x *MinFundingSettings) ProtoReflect() protoreflect.Message {
	mi := &file_proto_funding_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MinFundingSettings.ProtoReflect.Descriptor instead.
func (*MinFundingSettings) Descriptor() ([]byte, []int) {
	return file_proto_funding_proto_rawDescGZIP(), []int{1}
}

func (x *MinFundingSettings) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *MinFundingSettings) GetMinRate() float64 {
	if x != nil {
		return x.MinRate
	}
	return 0
}

var File_proto_funding_proto protoreflect.FileDescriptor

const file_proto_funding_proto_rawDesc = "" +
	"\n" +
	"\x13proto/funding.proto\x12\ttransport\"\xba\x01\n" +
	"\vFundingRate\x12\x1a\n" +
	"\bexchange\x18\x01 \x01(\tR\bexchange\x12\x16\n" +
	"\x06symbol\x18\x02 \x01(\tR\x06symbol\x12\x12\n" +
	"\x04rate\x18\x03 \x01(\x01R\x04rate\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\x12\x1d\n" +
	"\n" +
	"volume_24h\x18\x05 \x01(\x01R\tvolume24h\x12&\n" +
	"\x0fvolume_usdt_24h\x18\x06 \x01(\x01R\rvolumeUsdt24h\"G\n" +
	"\x12MinFundingSettings\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x19\n" +
	"\bmin_rate\x18\x02 \x01(\x01R\aminRateB1Z/github.com/petrixs/cr-transport-bus/proto;protob\x06proto3"

var (
	file_proto_funding_proto_rawDescOnce sync.Once
	file_proto_funding_proto_rawDescData []byte
)

func file_proto_funding_proto_rawDescGZIP() []byte {
	file_proto_funding_proto_rawDescOnce.Do(func() {
		file_proto_funding_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_funding_proto_rawDesc), len(file_proto_funding_proto_rawDesc)))
	})
	return file_proto_funding_proto_rawDescData
}

var file_proto_funding_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_funding_proto_goTypes = []any{
	(*FundingRate)(nil),        // 0: transport.FundingRate
	(*MinFundingSettings)(nil), // 1: transport.MinFundingSettings
}
var file_proto_funding_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_funding_proto_init() }
func file_proto_funding_proto_init() {
	if File_proto_funding_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_funding_proto_rawDesc), len(file_proto_funding_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_funding_proto_goTypes,
		DependencyIndexes: file_proto_funding_proto_depIdxs,
		MessageInfos:      file_proto_funding_proto_msgTypes,
	}.Build()
	File_proto_funding_proto = out.File
	file_proto_funding_proto_goTypes = nil
	file_proto_funding_proto_depIdxs = nil
}
